
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"


[[headers]]
  for = "/.netlify/functions/cms-proxy"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-App-Token"


[dev]
  command = "npm run dev"         
  targetPort = 3003                
  port = 3002                     
  functions = "netlify/functions"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200