# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]

  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"


[[headers]]
  for = "/.netlify/functions/cms-proxy"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-App-Token"